### ISSUE TITLE
已经有线上项目运行了吗？

### ISSUE THREAD

**Issue by bostin** [phpmicroservice/pms#1]
如题

**Comment by dongasai** [comment]
感谢您的关注,还没有,O(∩_∩)O~ ,第一个项目开发中,一个月内**千万别用,千万别用,千万别用**,重要的事情说三遍,我自己都跑不起来,刚从项目中把框架扒出来

**Comment by dongasai** [comment]
可以看看代码,都不深奥,提提路线图意见,代码意见都可以

**Comment by bostin** [comment]
好吧
先给你点个星星
